[project]
name = "todo-planner"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.6",
    "django-environ>=0.12.0",
    "psycopg>=3.2.10",
]

[dependency-groups]
dev = [
    "django-extensions>=4.1",
    "ipython>=9.5.0",
    "psycopg-binary>=3.2.10",
]
