# Generated by Django 5.2.6 on 2025-10-07 13:29

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_link", "0001_initial"),
        ("apps_project", "0005_alter_category_color"),
        ("apps_task", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("priority", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("do_today", "Do Today"),
                            ("in_progress", "In Progress"),
                            ("testing", "Testing"),
                            ("done", "Done"),
                            ("stuck", "STUCK"),
                            ("suspended", "Suspended"),
                        ],
                        default="task",
                        max_length=50,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        null=True,
                        validators=[apps.core.validators.is_hex_color],
                    ),
                ),
                ("labels", models.ManyToManyField(to="apps_task.label")),
                ("links", models.ManyToManyField(to="apps_link.link")),
                (
                    "sub_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps_project.subproject",
                    ),
                ),
            ],
            options={
                "ordering": ("-priority",),
                "default_related_name": "tasks",
                "unique_together": {("name", "sub_project")},
            },
        ),
    ]
