# Generated by Django 5.2.6 on 2025-10-07 11:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ("modified_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("end_date__isnull", False),
                                ("start_date__isnull", False),
                            ),
                            models.Q(
                                ("end_date__isnull", True),
                                ("start_date__isnull", False),
                            ),
                            models.Q(
                                ("end_date__isnull", True), ("start_date__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="apps_project_project_end_date_check",
                    )
                ],
            },
        ),
    ]
