# Generated by Django 5.2.6 on 2025-10-07 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("color", models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
    ]
