# Generated by Django 5.2.6 on 2025-10-07 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_project", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="sub_projects", to="apps_project.category"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apps_project.project",
                    ),
                ),
            ],
            options={
                "ordering": ("modified_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("end_date__isnull", False),
                                ("start_date__isnull", False),
                            ),
                            models.Q(
                                ("end_date__isnull", True),
                                ("start_date__isnull", False),
                            ),
                            models.Q(
                                ("end_date__isnull", True), ("start_date__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="apps_project_subproject_end_date_check",
                    )
                ],
                "unique_together": {("project", "name")},
            },
        ),
    ]
