# Generated by Django 5.2.6 on 2025-10-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_project", "0003_subproject"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="apps_project_project_end_date_start_date_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="subproject",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="apps_project_subproject_end_date_start_date_check",
            ),
        ),
    ]
