# Generated by Django 5.2.6 on 2025-10-07 13:29

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apps_project",
            "0004_project_apps_project_project_end_date_start_date_check_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[apps.core.validators.is_hex_color],
            ),
        ),
    ]
