# Generated by Django 5.2.6 on 2025-10-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_link", "0001_initial"),
        ("apps_project", "0005_alter_category_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="links",
            field=models.ManyToManyField(related_name="projects", to="apps_link.link"),
        ),
    ]
