# Generated by Django 5.2.6 on 2025-10-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_link", "0001_initial"),
        ("apps_project", "0006_project_links"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subproject",
            options={
                "default_related_name": "sub_projects",
                "ordering": ("modified_at",),
            },
        ),
        migrations.AddField(
            model_name="subproject",
            name="links",
            field=models.ManyToManyField(to="apps_link.link"),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="categories",
            field=models.ManyToManyField(to="apps_project.category"),
        ),
    ]
